var SUPPORTED_BLOCK_TYPES={
    'code-block': true,
    'custom-code-block':true,
    'custom-code-block-bash':true,
    'custom-code-block-c':true,
    'custom-code-block-coffeescript':true,
    'custom-code-block-cpp':true,
    'custom-code-block-csharp':true,
    'custom-code-block-css':true,
    'custom-code-block-dart':true,
    'custom-code-block-docker':true,
    'custom-code-block-elixir':true,
    'custom-code-block-erlang':true,
    'custom-code-block-fortran':true,
    'custom-code-block-git':true,
    'custom-code-block-go':true,
    'custom-code-block-groovy':true,
    'custom-code-block-haskell':true,
    'custom-code-block-markup':true,
    'custom-code-block-jade':true,
    'custom-code-block-java':true,
    'custom-code-block-javascript':true,
    'custom-code-block-json':true,
    'custom-code-block-jsx':true,
    'custom-code-block-makefile':true,
    'custom-code-block-markdown':true,
    'custom-code-block-matlab':true,
    'custom-code-block-nginx':true,
    'custom-code-block-perl':true,
    'custom-code-block-php':true,
    'custom-code-block-python':true,
    'custom-code-block-ruby':true,
    'custom-code-block-r':true,
    'custom-code-block-scala':true,
    'custom-code-block-scss':true,
    'custom-code-block-sql':true,
    'custom-code-block-swift':true,
    'custom-code-block-typescript':true,
    'custom-code-block-vim':true,
    'custom-code-block-yaml':true
}

var SUPPORTED_LANG={
    bash:true,
    c:true,
    clike:true,
    coffeescript:true,
    cpp:true,
    csharp:true,
    css:true,
    dart:true,
    docker:true,
    elixir:true,
    erlang: true,
    fortran:true,
    git:true,
    go:true,
    groovy:true,
    haskell:true,
    java:true,
    javascript:true,
    json:true,
    jsx:true,
    makefile:true,
    markdown:true,
    markup:true,
    matlab: true,
    nginx:true,
    perl:true,
    php:true,
    python:true,
    r:true,
    ruby:true,
    scala:true,
    scss:true,
    sql:true,
    swift:true,
    typescript:true,
    vim:true,
    yaml:true
}

module.exports={
    SUPPORTED_LANG:SUPPORTED_LANG,
    SUPPORTED_BLOCK_TYPES: SUPPORTED_BLOCK_TYPES
}
